//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3_ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        public long ID { get; set; }
        [Required(ErrorMessage = "Bắt buộc.")]
        [DisplayName("Tên sản phẩm")]
        public string Name { get; set; }
        [DataType(DataType.Upload)]
        [DisplayName("Hình ảnh")]
        public HttpPostedFileBase ImageFileUpload { get; set; }
        [Required(ErrorMessage = "Bắt buộc.")]
        [DisplayName("Giá")]
        public long Price { get; set; }
        [Required(ErrorMessage = "Bắt buộc.")]
        [DisplayName("Danh mục")]
        public string Category { get; set; }
        public string ImagePath { get; set; }
        [Required(ErrorMessage = "Bắt buộc.")]
        [DisplayName("Số lượng")]
        public long RemainStocks { get; set; }

        public Category Category_EnumValue { get; set; }
    }
}