//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3_ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long ID { get; set; }
        public System.DateTime Tháng { get; set; }
        public long Doanh_thu_Máy_tính { get; set; }
        public long Doanh_thu_Điện_thoại { get; set; }
        public long Doanh_thu_Phụ_kiện { get; set; }
        public long Doanh_thu_Khác { get; set; }
        public long Số_sản_phẩm_bán_được_Máy_tính { get; set; }
        public long Số_sản_phẩm_bán_được_Điện_thoại { get; set; }
        public long Số_sản_phẩm_bán_được_Phụ_kiện { get; set; }
        public long Số_sản_phẩm_bán_được_Khác { get; set; }
        public long Số_sản_phẩm_còn_lại_Máy_tính { get; set; }
        public long Số_sản_phẩm_còn_lại_Điện_thoại { get; set; }
        public long Số_sản_phẩm_còn_lại_Phụ_kiện { get; set; }
        public long Số_sản_phẩm_còn_lại_Khác { get; set; }
    }
}
